

enum ListPermissions {
    ADMINISTRADOR_PERMISOS = 'ADMINISTRADOR_PERMISOS',
    LEER_NOTICIAS = 'LEER_NOTICIAS',
    VER_LISTADO_VACACIONES = 'VER_LISTADO_VACACIONES',
    CREAR_NOTICIAS = 'CREAR_NOTICIAS',
  }
  
  export default ListPermissions;