

enum Permissions {
    NOTICIAS = 'NOTICIAS',
    GENERAL = 'GENERAL',
    RECURSOS_HUMANOS = 'RECURSOS_HUMANOS',
    CONTABILIDAD = 'CONTABILIDAD',
    ADMINISTRADOR = 'ADMINISTRADOR',
    DIRECTOR = 'DIRECTOR',
    ADMINISTRADOR_PERMISOS = 'ADMINISTRADOR_PERMISOS',
    SUPER_ADMINISTRADOR = 'SUPER_ADMINISTRADOR',
    SISTEMA_ARCHIVOS_ADMINISTRADOR = 'SISTEMA_ARCHIVOS_ADMINISTRADOR'

}

export default Permissions;